feat: PIP chat during screenshare
100mslive/web-sdks pull request #3050
Opened 2024-07-01 04:02 UTC by KaustubhKumar05

- [ ] Auto start PIP chat when screenshare is enabled
- [ ] Show the last 5 messages
- [ ] Receiver validation 
- [ ] CSS fixes 
- [ ] Refactor

2024-07-12 05:16 UTC, raviteja83 commented
spacing is little bit off. message and send message should start at same place. if it is not straightforward, we can live with it.

2024-07-12 05:21 UTC, KaustubhKumar05 commented
> spacing is little bit off. message and send message should start at same place. if it is not straightforward, we can live with it.

Can update, should be a small fix

2024-07-12 12:17 UTC, raviteja83 commented on packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
> +      const chatContainer = pipWindow.document.getElementById('chat-container');
can we not extract it out of desktop options?

2024-07-12 12:18 UTC, raviteja83 commented on packages/roomkit-react/src/Prebuilt/components/PIP/PIPChat.tsx
> +      setUnreadMessageCount(count);
what is this for?

2024-07-12 15:12 UTC, raviteja83 requested changes

2024-07-12 15:12 UTC, raviteja83 commented on packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
> +      const pipChatInput = pipWindow.document.getElementsByTagName('textarea')[0];
better to have ids for everything. there will be less chance of another textarea but better to have ids.

2024-07-15 06:33 UTC, KaustubhKumar05 commented on packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
> +          await hmsActions.sendGroupMessage(pipChatInput.value.trim(), [selection]);
Yeah, just broadcast is requested by clients. Role specific was requested by product

2024-07-15 07:21 UTC, KaustubhKumar05 commented on packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
> +      const chatContainer = pipWindow.document.getElementById('chat-container');
Can make this a hook so it will be cleaner and easier to move around if we are updating the placement. Does that work?

2024-07-15 07:29 UTC, KaustubhKumar05 commented on packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
> +      const chatContainer = pipWindow.document.getElementById('chat-container');
Creating a container for this

2024-07-15 07:54 UTC, KaustubhKumar05 commented on packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
> +      const chatContainer = pipWindow.document.getElementById('chat-container');
Desktop options is always present on screen, when it unmounts the chat window is closed. Will check for alternatives

2024-07-15 16:45 UTC, raviteja83 commented on packages/roomkit-react/src/Prebuilt/components/PIP/usePIPChat.tsx
> +              if (messageId) observer.observe(message as Element);
no need to observe the new message notifi no? this can go in else of above.

2024-07-15 16:46 UTC, raviteja83 commented on packages/roomkit-react/src/Prebuilt/components/PIP/usePIPChat.tsx
> +      const mutationObserver = new MutationObserver(mutations => {
this and intersection observer also to be cleaned up

2024-07-15 16:46 UTC, raviteja83 commented on packages/roomkit-react/src/Prebuilt/components/PIP/usePIPChat.tsx
> +      if (sendBtn && hmsActions && pipChatInput && !sendFuncAdded.current) {
why is all of this needed?

2024-07-15 16:46 UTC, raviteja83 commented on packages/roomkit-react/src/Prebuilt/components/PIP/usePIPChat.tsx
> +      const mutationObserver = new MutationObserver(mutations => {
this and intersection observer also to be cleaned up

2024-07-16 07:11 UTC, KaustubhKumar05 commented on packages/roomkit-react/src/Prebuilt/components/PIP/usePIPChat.tsx
> +              if (messageId) observer.observe(message as Element);
This is needed, observer marks this as read once it comes into view

2024-07-16 07:12 UTC, KaustubhKumar05 commented on packages/roomkit-react/src/Prebuilt/components/PIP/usePIPChat.tsx
> +      if (sendBtn && hmsActions && pipChatInput && !sendFuncAdded.current) {
Updated

2024-07-16 11:20 UTC, raviteja83 approved these changes

2024-07-16 11:21 UTC, merged