Fix: Removed europe region and converted jitter values from s to ms
100mslive/web-sdks pull request #3417
Opened 2024-12-11 11:31 UTC by monkCommits

# Description

Removed the region Europe as it is not needed as of now.
Converted jitter values from s to ms.

_List which issues are fixed by this PR. You must list at least one issue._

---

-

### Pre-launch Checklist

- [ ] The [Documentation] is updated accordingly, or this PR doesn't require it.
- [ ] I updated/added relevant documentation.
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making, or this PR is test-exempt.
- [ ] All existing and new tests are passing.

### Merging:
- Squash merge to dev
- Merge commit to publish-alpha and main

[Documentation]: https://www.100ms.live/docs

2024-12-11 11:54 UTC, KaustubhKumar05 submitted a review, later dismissed

2024-12-11 12:06 UTC, ygit requested changes

2024-12-11 12:06 UTC, ygit commented on packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
> -          <DetailedInfo title="Jitter" value={`${stats.jitter} s`} />
@monkCommits why is it removed here?

2024-12-11 12:06 UTC, ygit commented on packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
> -          <DetailedInfo title="Jitter" value={`${stats.jitter} s`} />
Similarly, @monkCommits why is it removed?

2024-12-11 12:19 UTC, ygit approved these changes
LGTM

2024-12-11 12:24 UTC, KaustubhKumar05 commented on packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
> +          <DetailedInfo title="Jitter" value={`${stats.jitter} s`} />
This should also be in ms

2024-12-11 12:24 UTC, KaustubhKumar05 commented on packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
> +          <DetailedInfo title="Jitter" value={`${stats.jitter} s`} />
Convert this too, we need it to be consistent and ms everywhere

2024-12-11 17:57 UTC, monkCommits commented on packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
> +          <DetailedInfo title="Jitter" value={`${stats.jitter} s`} />
@KaustubhKumar05 updated

2024-12-12 05:50 UTC, KaustubhKumar05 approved these changes

2024-12-12 05:51 UTC, KaustubhKumar05 commented
Let's merge this after the release

2024-12-12 05:52 UTC, ygit approved these changes
LGTM

2024-12-12 05:52 UTC, merged